package com.yuanxin.clan.mvp.dao;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

//    private final DaoConfig productBeanDaoConfig;
//    private final DaoConfig memberEntityDaoConfig;
//    private final DaoConfig restingOrderEntityDaoConfig;

//    private final ProductBeanDao productBeanDao;
//    private final MemberEntityDao memberEntityDao;
//    private final RestingOrderEntityDao restingOrderEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

//        productBeanDaoConfig = daoConfigMap.get(ProductBeanDao.class).clone();
//        productBeanDaoConfig.initIdentityScope(type);
//
//        memberEntityDaoConfig = daoConfigMap.get(MemberEntityDao.class).clone();
//        memberEntityDaoConfig.initIdentityScope(type);
//
//        restingOrderEntityDaoConfig = daoConfigMap.get(RestingOrderEntityDao.class).clone();
//        restingOrderEntityDaoConfig.initIdentityScope(type);
//
//        productBeanDao = new ProductBeanDao(productBeanDaoConfig, this);
//        memberEntityDao = new MemberEntityDao(memberEntityDaoConfig, this);
//        restingOrderEntityDao = new RestingOrderEntityDao(restingOrderEntityDaoConfig, this);
//
//        registerDao(ProductBean.class, productBeanDao);
//        registerDao(MemberEntity.class, memberEntityDao);
//        registerDao(RestingOrderEntity.class, restingOrderEntityDao);
    }

    public void clear() {
//        productBeanDaoConfig.getIdentityScope().clear();
//        memberEntityDaoConfig.getIdentityScope().clear();
//        restingOrderEntityDaoConfig.getIdentityScope().clear();
    }
//
//    public ProductBeanDao getProductBeanDao() {
//        return productBeanDao;
//    }
//
//    public MemberEntityDao getMemberEntityDao() {
//        return memberEntityDao;
//    }
//
//    public RestingOrderEntityDao getRestingOrderEntityDao() {
//        return restingOrderEntityDao;
//    }

}
